### ISSUE TITLE
Show latest dabis by default. 

### ISSUE THREAD

**Issue by fluentmoheshwar** [jonogon/jonogon-mono#111]
The website currently shows most voted petitions by default. Which leads to less votes on newer petitions.

https://jonogon.org/petitions/653

**Comment by 0xriyadh** [comment]
Just simply showing the new দাবিs first won't work as well, as important দাবিs might get behind the new দাবিs. Just because a দাবি is new, doesn't mean it's more important. The team is working on to come up with an algorithm that will address this issue and give a proper solution to handle the scenario. Thank you.
